1816:
Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 158, in checkout_form
    driver.find_element_by_link_text('Check Out').click()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Check Out"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 530, in execute_program
    checkout_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 161, in checkout_form
    checkin_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 233, in checkin_form
    ': Has no form to check in')
NoCheckedOutFormException: 1816: Has no form to check in
 1816: Has no form to check in
1832:
Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 158, in checkout_form
    driver.find_element_by_link_text('Check Out').click()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Check Out"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 530, in execute_program
    checkout_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 161, in checkout_form
    checkin_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 233, in checkin_form
    ': Has no form to check in')
NoCheckedOutFormException: 1832: Has no form to check in
 1832: Has no form to check in
1874:
Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 158, in checkout_form
    driver.find_element_by_link_text('Check Out').click()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Check Out"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 530, in execute_program
    checkout_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 161, in checkout_form
    checkin_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 233, in checkin_form
    ': Has no form to check in')
NoCheckedOutFormException: 1874: Has no form to check in
 1874: Has no form to check in
1889:
Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 158, in checkout_form
    driver.find_element_by_link_text('Check Out').click()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Check Out"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 530, in execute_program
    checkout_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 161, in checkout_form
    checkin_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 233, in checkin_form
    ': Has no form to check in')
NoCheckedOutFormException: 1889: Has no form to check in
 1889: Has no form to check in
1890:
Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 158, in checkout_form
    driver.find_element_by_link_text('Check Out').click()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Check Out"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 530, in execute_program
    checkout_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 161, in checkout_form
    checkin_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 233, in checkin_form
    ': Has no form to check in')
NoCheckedOutFormException: 1890: Has no form to check in
 1890: Has no form to check in
1891:
Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 158, in checkout_form
    driver.find_element_by_link_text('Check Out').click()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Check Out"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 530, in execute_program
    checkout_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 161, in checkout_form
    checkin_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 233, in checkin_form
    ': Has no form to check in')
NoCheckedOutFormException: 1891: Has no form to check in
 1891: Has no form to check in
1892:
Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 158, in checkout_form
    driver.find_element_by_link_text('Check Out').click()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Check Out"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 530, in execute_program
    checkout_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 161, in checkout_form
    checkin_form(driver, asset_number)
  File "S:/Engineering/Jake/mc-completing-asset-accession-forms/mc_completing_asset_accession_forms.py", line 233, in checkin_form
    ': Has no form to check in')
NoCheckedOutFormException: 1892: Has no form to check in
 1892: Has no form to check in
